version: '3'

services:
  front:
    build: frontend
    depends_on:
      - web
    ports:
    - "80:80"
    restart: on-failure
  web:
    build: backend
    depends_on:
      - db
    ports:
      - "8080:8080"
    restart: on-failure

  db:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_DB: 'dbusca'
      POSTGRES_USER: 'api_user'
      POSTGRES_PASSWORD: 'root'
    ports:
      - '5432:5432'
    volumes:
      - dbusca-db:/var/lib/database

volumes:
  dbusca-db: